config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  devise_for :admins, only: :session
  resources :users do
    get :doctor_profile, on: :collection
  end

  # Routes for Patient Reports
  get 'reports/:patient_id', to:'reports#index'
  get 'reports/:patient_id/:category', to:'reports#category'
  get 'prescription/:patient_id', to: 'reports#prescription'
  post 'add_prescription/:patient_id', to: 'reports#add_prescription'
  delete 'delete_reports/:report_id', to: 'reports#delete_reports', as: 'delete_reports'
  # Routes for HomePages
  get 'homepage', to: 'home#homepage'
  get 'get_reports', to: 'home#get_reports'
  root to: 'home#homepage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :contact, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include InitializeFirestore

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :contact ])
  end

end

app/controllers/concerns/initialize_firestore.rb
require 'net/http'
require 'uri'
require 'json'
require "google/cloud/firestore"

module InitializeFirestore
  extend ActiveSupport::Concern

  def create_firestore
    @firestore = Google::Cloud::Firestore.new project_id: 'login-app-dc785', keyfile: SECRET_KEY_FILE
    @users_ref = @firestore.col('Users')
  end

  private
  SECRET_KEY_FILE = {
    "type": "service_account",
    "project_id": "login-app-dc785",
    "private_key_id": "0a56bc8991762d05456011637dc7c94976c2e88a",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4S/RUCo96anSz\n5cUYG8vEL2xdvMgHg/3rrR4VrVLD1UORbyUSKIQ+W3geBwOPLRJ9tkVChrdqhvGE\n0ucavoRGdnJuhesMxQoprfceWMnPfnztWTydFwLcAX/jtmudOS/R/BntOpIW6WcB\nb2WskqKaoKhK7O8zoZRz4b+3fVFATc11LyUaRNzj/09wVWCvHaQigV9010h9zgmR\nnC43UBUY7O9nVbseqtL2DV1XwCLpknG1KD9sUqPxjLFDzauSg9aG9P+Y3/VbYHcR\nufLDsoxyEshsyoaaZGD/9hH0dWngUGKkGAoiBz2QxGfqVFQuy6tDSpKiLL6oBjPh\nMgi+LkZBAgMBAAECggEACjDSAHUqiKB7Fkj/6GS+FFmydm72SRsadvYWRijUvSUt\nZKz2ie3hXSDZ8CAfaWL6xSaHZyWznfF7CKcQViVfg1Vwn62qSQUauiIHWn9anm1+\nOzIeZMnVU8TF9Xmccv/K5gO4i8p7skZi9px6LOwZT29PiwAVvH9EahF7NEpazDFA\n2+XqcG8R84n/68z/wiV1R75sQTWcS2PnYN6M6sj43XIUHhcYWVqAw0VQ1NaYdfAC\nI9IRBEXZyioBp0KXc2aaCkInYsM8DCLyup7TRsyYy6hD81vexiKJfannefyS+a2S\nry6FfKlug55IY16ib60lFdB4AJfqNfFFPF/3QU6+CQKBgQD9HaVoNCIJFT7bLsjo\nUBDYrO2T++0YlytXOOfva+pTVzNK3w81F3GjHG9Sf1ebrx6+IkrmEls7A1nc9djR\nOwOHkbn823tKVAjYkztSY70J1u7KXwscVQGSurUiOSlCDRRpOBTT4u/MD+FJISHj\nctE+YN7WobE23ypoRWUVzW+GOQKBgQC6ZY8Qs1flnFWFjRSDzhyCVHVEute7QJN4\nzDEu2YipT7ZD2tU1UFcRwS/nP407gYVG9IEwiAaliC2z9TZHkIzcSdH2ukbF71m/\ndjL5upx8Jpf4mv4cIZDbGHuECS1pOzC3brxEFpn4O6m2vr2F3GgCRR0T9NUVcSOy\naguL/GkASQKBgD0JtSWXzM1b7jh048YB6M4XhYM2MUrIyY7TDjtSTsOiN6BKgiRP\nbvvik4XVZ48Hf+Zh5qXsr0tf13/NWWe7T3KV1cAAPY8DDM8NUjTgEGobBqKOoONI\nLITxuVRzbFudQ9rLx1oBU8pl2fIEp2NuAL+GJLalb1LIJjXW5jWHwOkhAoGAQ9aq\nlv1uxBZ92bla+g2NurFabMVDttbt1U0bqV1qq5RjVZbTei/fQIr7EELE+B9Pjl92\nlV8sbBp/57sbIjity47iZ9Wr5GYUV+aA7vrH8TdqoARo73wX6GWkro1YhbARLvGS\ne4VuTDYKsoQBHjL1d74HszesRb2DrG+D/FLFNGECgYA5G4no+grLnQnBDuweekIY\nDNBj5ah0p6lg5CXwmK7JdTOvPHTzcLTVgFUwtbdnIGmg+ZiFm/QkF1n38UfSDSR2\nfKdONnPfj3DD2jmAECvboODss8d95L4kV6hvygxCXvd3RTthT4+EMwT9ME3Fch5y\n+FstbbwRoVKA4ii+pX1FGg==\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-nk0a0@login-app-dc785.iam.gserviceaccount.com",
    "client_id": "114384118006331663699",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-nk0a0%40login-app-dc785.iam.gserviceaccount.com"
  }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :create_firestore

  def homepage; end

  def get_reports
    patient_id = params[:id].delete(' ')
    if patient_id.empty?
      redirect_to root_path, notice: 'Patient ID should not be empty'
    elsif @users_ref.doc(patient_id).get.exists?
      redirect_to "/reports/#{patient_id}"
    else
      redirect_to root_path, alert: 'Please Enter a Valid Patient ID'
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :create_firestore
  before_action :authenticate_doctor!, only:[:prescription, :add_prescription]
  before_action :authenticate_admin!, only:[:delete_reports]
  before_action :get_user_and_reports, except: [:prescription]
  before_action :get_prescription_ref, only: [:add_prescription, :prescription]

  def index
    @reports = @reports_ref.get
    @count = 0
  end

  def category
    @reports = @reports_ref.where("category", "=", params[:category]).get
    @count = 0
  end

  def prescription
    @patient_id = params[:patient_id]
    @prescriptions = @prescription_ref.get
  end

  def add_prescription
    prescription_text = params[:prescription]
    if prescription_text.empty?
      redirect_to "/prescription/#{params[:patient_id]}", alert: 'Prescription Text is Empty'
    else
      prescription_hash = {
        doctorName: current_doctor.name,
        doctorEmail: current_doctor.email,
        createdAt: DateTime.now,
        prescription: prescription_text
      }
      @prescription_ref.add prescription_hash
      # sending email to user
      get_patient_email
      PrescriptionMailer.send_prescription_email(@email,current_doctor.email, current_doctor.name, prescription_text).deliver
      redirect_to "/prescription/#{params[:patient_id]}", notice: 'Prescription Added'
    end
  end

  def delete_reports
    @report = @reports_ref.doc(params[:report_id])
    if @report.get.exists?
      @report.delete
      redirect_to get_reports_path(patient_id: params[:patient_id])
    end
  end

  private

  def get_prescription_ref
    @prescription_ref = @users_ref.doc(params[:patient_id]).col("Prescriptions")
  end

  def get_user_and_reports
    @user = @users_ref.doc(params[:patient_id]).get
    @categories = @users_ref.doc(params[:patient_id]).col("Categories").get
    @reports_ref = @users_ref.doc(params[:patient_id]).col("Reports")
  end

  def get_patient_email
    @email =  @users_ref.doc(params[:patient_id]).get[:email]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :create_firestore
  before_action :authenticate_admin!, except: [:doctor_profile]
  before_action :authenticate_doctor!, only:[:doctor_profile]


  def index
    @users = @users_ref.get
  end

  def show
    @user = @users_ref.doc(params[:id]).get
    @reports = @users_ref.doc(params[:id]).col("Reports").get
    @count = 0
  end

  def destroy
    @user = @users_ref.doc(params[:id])
    if @user.get.exists?
      @user.delete
      redirect_to users_path
    end
  end

  def doctor_profile
    @doctor = current_doctor
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    if request.path == path
      'active'
    else
      ''
    end
  end

  def active_category(category, current_category)
    if category == current_category
      'btn btn-dark'
    else
      'btn btn-outline-dark'
    end
  end

  def is_reports_path
    request.path.include? "/reports/#{params[:patient_id]}"

  end

  def is_prescription
    request.path == "/prescription/#{params[:patient_id]}"
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
<!--  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
<!--  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />-->
<%# end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/doctors/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/doctors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:'btn btn-outline-primary '%><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) , class:'btn btn-outline-primary mb-3 '%><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/home/homepage.html.erb
<div class="container" style="margin-top: 150px">
  <div class="row">
    <div class="col-lg-6">
      <%= form_with url: get_reports_path, method: :get, local:true do |f| %>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Patient Id</label>
          <%= f.text_field :id, autofocus: true, autocomplete: "Patient Id", class: 'form-control' %>
        </div>

        <div class="actions mb-3">
          <%= f.submit "Get Reports", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectPRD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!--  Nav Bar-->
  <%= render 'shared/navbar' %>

  <!--    BuiltIn flash messages-->
  <% if flash[:notice] %>
    <p class="alert alert-primary mx-5 my-2"><%= notice %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="alert alert-danger mx-5 my-2"><%= alert %></p>
  <% end %>

  <%= yield %>
  </body>
</html>

app/views/reports/_prescriptions.html.erb
<div class="border rounded p-2">
  <h5 class="mb-4 ">Prescriptions</h5>

  <% @prescriptions.each do |prescription| %>
    <div class="card my-3">
      <div class="card-body">
        <h5 class="card-title"><%= prescription[:doctorName] %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= prescription[:doctorEmail] %></h6>
        <p class="card-text"><%= prescription[:prescription] %></p>
        <div class="card-footer"><%= prescription[:createdAt] %></div>
      </div>
    </div>
  <% end %>

</div>

app/views/reports/category.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-lg-4">
      <h5>Patient's Details</h5>
      <div class="card mt-4">
        <div class="card-header">
          <%= @user[:userName] %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Email: <%= @user[:email] %></li>
          <li class="list-group-item">Address: <%= @user[:address] %></li>
          <li class="list-group-item">Contact: <%= @user[:contact] %></li>
          <li class="list-group-item">ID: <%= @user.document_id %></li>
        </ul>
      </div>

      <h5 class="my-4">Categories</h5>
      <% @categories.each do |category| %>
        <%= link_to "/reports/#{params[:patient_id]}/#{category[:name]}", class: "d-flex btn my-3 p-2 #{active_category(category[:name], params[:category])}" do %>
          <i class="bi bi-folder" style="color: goldenrod"></i>
          <div class="ms-3"><%= category[:name] %></div>
        <% end %>
      <% end %>

    </div>

    <div class="col-lg-8">
      <h5 class=" mb-4"><%= params[:category].pluralize %></h5>
      <div class="border rounded p-2">
        <% @reports.each do |report| %>
          <% @count += 1 %>
          <div class="border border-dark rounded my-3">
            <img src="<%= report[:downloadUrl] %>" class="img-fluid rounded" alt="Report" width="100%">
            <br>
            <h6 class="px-3 pt-3">Category</h6>
            <p class="px-3 pb-3" style="white-space: pre"><%= report[:category] %></p>
          </div>
        <% end %>
        <%= @count == 0 ? 'No Report For This User' : '' %>
      </div>
    </div>
  </div>

</div>

app/views/reports/index.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-lg-4">
      <h5>Patient's Details</h5>
      <div class="card mt-4">
        <div class="card-header">
          <%= @user[:userName] %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Email: <%= @user[:email] %></li>
          <li class="list-group-item">Address: <%= @user[:address] %></li>
          <li class="list-group-item">Contact: <%= @user[:contact] %></li>
          <li class="list-group-item">ID: <%= @user.document_id %></li>
        </ul>
      </div>

      <h5 class="my-4">Categories</h5>
      <% @categories.each do |category| %>
        <%= link_to "/reports/#{params[:patient_id]}/#{category[:name]}", class: 'd-flex btn btn-outline-dark my-3 p-2' do %>
          <i class="bi bi-folder" style="color: goldenrod"></i>
          <div class="ms-3"><%= category[:name] %></div>
        <% end %>
      <% end %>

    </div>

    <div class="col-lg-8">
      <h5 class=" mb-4">Patient's Reports</h5>
      <div class="border rounded p-2">
        <% @reports.each do |report| %>
          <% @count += 1 %>
          <div class="border border-dark rounded my-3">
            <img src="<%= report[:downloadUrl] %>" class="img-fluid rounded" alt="Report" width="100%">
            <br>
            <h6 class="px-3 pt-3">Category</h6>
            <p class="px-3 pb-1" style="white-space: pre"><%= report[:category] %></p>
            <br>
            <% if admin_signed_in? %>
              <%#= link_to 'Delete', delete_reports_path(report_id: report.document_id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger ms-3 mb-3' %>
            <% end %>
          </div>
        <% end %>
        <%= @count == 0 ? 'No Report For This User' : '' %>
      </div>
    </div>
  </div>

</div>

app/views/reports/prescription.html.erb
<div class="row m-5">

  <div class="col-lg-4">
    <h5 class="mb-3">Add Prescription</h5>
    <%= form_with url: "/add_prescription/#{@patient_id}",method: :post, local: true do |f| %>
      <%= f.text_area :prescription, size: "0x15", class: 'form-control mb-3'%>
      <%= f.submit 'Add Prescription', class: 'btn btn-primary mb-5' %>
    <% end %>
  </div>

  <div class="col-lg-8">
    <%= render 'prescriptions' %>
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Patient Reports Digitization</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if admin_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link #{active_class root_path}" %>
          </li>

          <li>
            <%= link_to '<i class="bi bi-wallet"></i> All Users'.html_safe, users_path, class: "nav-link #{active_class users_path}" %>
          </li>
        <% end %>

        <% if doctor_signed_in? && (is_reports_path || is_prescription) %>
          <%= link_to 'Add-View Prescription', "/prescription/#{params[:patient_id]}", class: "nav-link #{active_class "/prescription/#{params[:patient_id]}"}" %>
        <% end %>

        <% if is_reports_path %>
          <% unless doctor_signed_in? %>
            <%= link_to 'Sign In as Doctor', new_doctor_session_path, class: "nav-link  #{active_class new_doctor_session_path}" %>
          <% end %>
        <% end %>

        <% if doctor_signed_in? %>
        <%= link_to 'View Profile', doctor_profile_users_path, class: "nav-link  #{active_class doctor_profile_users_path}" %>
        <% end %>

        <% unless admin_signed_in? || doctor_signed_in? %>

        <% end %>
      </ul>

      <form class="d-flex">

        <% if doctor_signed_in? %>
          <div class="form-control btn btn-danger me-2">
            <%= link_to '<i class="bi bi-box-arrow-right"></i> Sign out'.html_safe, destroy_doctor_session_path, method: :delete, class: "nav-link" %>
          </div>
        <% end %>


        <% if admin_signed_in? %>
          <div class="form-control btn btn-danger me-2">
            <%= link_to '<i class="bi bi-box-arrow-right"></i> Sign out'.html_safe, destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </div>
        <% end %>

      </form>


    </div>
  </div>
  </body>
</nav>

app/views/users/doctor_profile.html.erb
<!------ Include the above in your HEAD tag ---------->

<div class="container" style="margin-top: 50px; padding: 20px;">
  <div class="row bg-light " style="padding: 20px; border-width: 3px; border-color: black; border-style: solid">
    <div class="col-sm-6 col-md-8">
      <h4><%= current_doctor.name %></h4>
      <br/>
      <small><cite title="San Francisco, USA"><%= current_doctor.contact %> <i class="glyphicon glyphicon-map-marker">
      </i></cite></small>
      <p>
        <br/>
        <i class="glyphicon glyphicon-envelope"></i><%= current_doctor.email %>
        <br/>
        <br/>
        <i class="glyphicon glyphicon-gift"></i><%= current_doctor.created_at %></p>

      <%= link_to 'Edit Profile', edit_doctor_registration_path(current_doctor), class:'btn btn-primary' %>
    </div>
    <div class="col-md-4 col-sm-6">
      <image src="https://cdn-icons-png.flaticon.com/512/504/504018.png" width="240px"></image>
    </div>
  </div>
</div>

<!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
<!--<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>-->
<!--<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>-->

app/views/users/index.html.erb
<div class="container my-4" >

  <div class="container table-responsive py-5">
    <table class="table table-striped table-bordered table-hover no-footer icon-fixed-width">
      <thead>
        <tr class="table-dark">
          <th>Email</th>
          <th>User Name</th>
          <th>Address</th>
          <th>Contact</th>
          <th>Document ID</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user[:email] %></td>
          <td><%= user[:userName] %></td>
          <td><%= user[:address] %></td>
          <td><%= user[:contact] %></td>
          <td><%= user.document_id %></td>
          <td class="text-center">
            <%= link_to 'Delete', { controller: users_path, action: :destroy, id: user.document_id }, method: :delete, data: {confirm:'Are you sure?'}, class: 'btn btn-danger me-3' %>
            <%= link_to 'View', "/reports/#{user.document_id}", class: 'btn btn-success me-3' %>
          </td>
        </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-lg-4">
      <h5>Patient's Details</h5>
      <div class="card mt-4">
        <div class="card-header">
          Current User
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Name: <%= @user[:userName] %></li>
          <li class="list-group-item">Email: <%= @user[:email] %></li>
          <li class="list-group-item">Address: <%= @user[:address] %></li>
          <li class="list-group-item">Contact: <%= @user[:contact] %></li>
          <li class="list-group-item">ID: <%= @user.document_id %></li>
        </ul>
      </div>
      <%= link_to '<i class="bi bi-trash3-fill"></i> Delete'.html_safe, { controller: users_path, action: :destroy, id: @user.document_id }, method: :delete, class: 'btn btn-danger my-5' %>
      <%= link_to '<i class="bi bi-pencil"></i> Edit'.html_safe, { controller: users_path, action: :destroy, id: @user.document_id }, method: :delete, class: 'btn btn-success my-5 ms-2' %>
    </div>

    <div class="col-lg-8">
      <h5 class=" mb-4">Patient's Reports</h5>
      <div class="border rounded p-2">
        <% @reports.each do |report| %>
          <% @count += 1 %>
          <div class="border border-dark rounded my-3">
            <img src="<%= report[:downloadUrl] %>" class="img-fluid rounded" alt="Report" width="100%">
            <br>
            <h6 class="px-3 pt-3">Ocr Data</h6>
            <p class="px-3 pb-3"><%= report[:ocrData] %>
          </div>
        <% end %>
        <%= @count == 0 ? 'No Report For This User' : '' %>
      </div>
    </div>
  </div>

</div>